# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.provider :virtualbox do |vb|
    vb.name = "FileSharingServer"
    vb.customize ["modifyvm", :id, "--natpf1", "nginx,TCP,,8080,,80"]
  end

  config.vm.provision :shell, :path => "provision/bootstrap.sh"
end


