USE [master]
GO

/****** Object:  Database [DocumentManager]    Script Date: 11/03/2017 13:41:40 ******/
CREATE DATABASE [DocumentManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DocumentManager', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\DocumentManager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DocumentManager_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\DocumentManager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DocumentManager] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DocumentManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DocumentManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DocumentManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DocumentManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DocumentManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DocumentManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [DocumentManager] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DocumentManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DocumentManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DocumentManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DocumentManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DocumentManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DocumentManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DocumentManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DocumentManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DocumentManager] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DocumentManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DocumentManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DocumentManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DocumentManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DocumentManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DocumentManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DocumentManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DocumentManager] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DocumentManager] SET  MULTI_USER 
GO

ALTER DATABASE [DocumentManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DocumentManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DocumentManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DocumentManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DocumentManager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DocumentManager] SET QUERY_STORE = OFF
GO

USE [DocumentManager]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DocumentManager] SET  READ_WRITE 
GO


USE [DocumentManager]
GO

/****** Object:  Table [dbo].[User]    Script Date: 11/03/2017 14:42:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[User](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Login] [varchar](50) NOT NULL,
	[Password] [varchar](200) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_User] UNIQUE NONCLUSTERED 
(
	[Login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [DocumentManager]
GO

/****** Object:  Table [dbo].[Session]    Script Date: 11/03/2017 14:42:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Session](
	[SecurityToken] [varchar](200) NOT NULL,
	[IdUser] [bigint] NOT NULL,
	[DateLastAccess] [datetime] NOT NULL,
 CONSTRAINT [PK_Session] PRIMARY KEY CLUSTERED 
(
	[SecurityToken] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Session]  WITH CHECK ADD  CONSTRAINT [FK_Session_User] FOREIGN KEY([IdUser])
REFERENCES [dbo].[User] ([Id])
GO

ALTER TABLE [dbo].[Session] CHECK CONSTRAINT [FK_Session_User]
GO

USE [DocumentManager]
GO

/****** Object:  Table [dbo].[Group]    Script Date: 11/03/2017 14:43:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Group](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[IdAdmin] [bigint] NOT NULL,
 CONSTRAINT [PK_Group] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_Group] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Group]  WITH CHECK ADD  CONSTRAINT [FK_Group_User] FOREIGN KEY([IdAdmin])
REFERENCES [dbo].[User] ([Id])
GO

ALTER TABLE [dbo].[Group] CHECK CONSTRAINT [FK_Group_User]
GO

USE [DocumentManager]
GO

/****** Object:  Table [dbo].[UserGroup]    Script Date: 11/03/2017 14:43:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserGroup](
	[IdUser] [bigint] NOT NULL,
	[IdGroup] [bigint] NOT NULL,
	[DateInclusionRequest] [datetime] NOT NULL,
	[DateInclusionApproval] [datetime] NULL,
 CONSTRAINT [PK_UserGroup] PRIMARY KEY CLUSTERED 
(
	[IdUser] ASC,
	[IdGroup] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[UserGroup]  WITH CHECK ADD  CONSTRAINT [FK_UserGroup_Group] FOREIGN KEY([IdGroup])
REFERENCES [dbo].[Group] ([Id])
GO

ALTER TABLE [dbo].[UserGroup] CHECK CONSTRAINT [FK_UserGroup_Group]
GO

ALTER TABLE [dbo].[UserGroup]  WITH CHECK ADD  CONSTRAINT [FK_UserGroup_User] FOREIGN KEY([IdUser])
REFERENCES [dbo].[User] ([Id])
GO

ALTER TABLE [dbo].[UserGroup] CHECK CONSTRAINT [FK_UserGroup_User]
GO

USE [DocumentManager]
GO

/****** Object:  Table [dbo].[Document]    Script Date: 11/03/2017 14:43:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Document](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[IdUser] [bigint] NOT NULL,
	[Filename] [varchar](200) NOT NULL,
	[IsPublic] [bit] NOT NULL,
	[IdGroup] [bigint] NULL,
 CONSTRAINT [PK_Document] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Document]  WITH CHECK ADD  CONSTRAINT [FK_Document_Group] FOREIGN KEY([IdGroup])
REFERENCES [dbo].[Group] ([Id])
GO

ALTER TABLE [dbo].[Document] CHECK CONSTRAINT [FK_Document_Group]
GO

ALTER TABLE [dbo].[Document]  WITH CHECK ADD  CONSTRAINT [FK_Document_User] FOREIGN KEY([IdUser])
REFERENCES [dbo].[User] ([Id])
GO

ALTER TABLE [dbo].[Document] CHECK CONSTRAINT [FK_Document_User]
GO

USE [DocumentManager]
GO

/****** Object:  Table [dbo].[Audit]    Script Date: 11/03/2017 14:43:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Audit](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[IdUser] [bigint] NOT NULL,
	[Date] [datetime] NOT NULL,
	[Object] [varchar](50) NOT NULL,
	[IdObject] [bigint] NOT NULL,
	[Action] [varchar](200) NOT NULL 
 CONSTRAINT [PK_Audit] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Audit]  WITH CHECK ADD  CONSTRAINT [FK_Audit_User] FOREIGN KEY([IdUser])
REFERENCES [dbo].[User] ([Id])
GO

ALTER TABLE [dbo].[Audit] CHECK CONSTRAINT [FK_Audit_User]
GO

